frameworkVersion: '>=1.28.0'

# NOTE: update this with your service name
service: spreadshare-image-optimizer

# Use the serverless-webpack plugin to transpile ES6
plugins:
  - serverless-webpack
  - serverless-offline

# serverless-webpack configuration
# Enable auto-packing of external modules
custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  serverless-offline:
    babelOptions:
      presets: ['env', 'flow']

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1
  versionFunctions: false
  environment: ${file(env.yml):${self:provider.stage}}

functions:
  upload:
    handler: src/handlers/upload.handler
    events:
      - http:
          method: post
          path: upload
          # request: 
          # parameters: 
          #    paths: 
          #      id: true
 
package:
  individually: true
